/**
 * chemistryEngine.ts — the rules core (spec §5).
 *
 * Everything here is a PURE function over a plain serialisable graph so it can be
 * unit-tested (see src/tests/chemistryEngine.test.ts) and reused by the reaction
 * engine, the campaign validator, the quiz and the JARVIS explanation card.
 *
 * The 3D editor never mutates chemistry directly: every gesture funnels through
 * `canBond()` / `canPlace()` and is rejected with a real chemistry reason.
 */

import { ELEMENT_TABLE, getElement, octetLimit, effectiveMaxValence } from './elements';

/** Re-exported so the rest of the app has a single chemistry import surface. */
export { effectiveMaxValence } from './elements';
import { lonePairs, formalCharge, formatCharge } from './formalCharge';
import { analyzeHybridization, type HybridizationInfo } from './hybridization';
import { classifyStability, type StabilityReport } from './stability';
import KNOWN_MOLECULES from './data/knownMolecules.json';

/* ------------------------------------------------------------------ types */

export type BondOrder = 1 | 2 | 3;
export type BondType = 'covalent' | 'aromatic' | 'ionic' | 'coordinate' | 'hydrogen';

export interface GraphAtom {
  id: string;
  element: string;
  /** Explicit formal charge placed by the user / ionic engine (0 by default). */
  charge?: number;
}

export interface GraphBond {
  id: string;
  a: string;
  b: string;
  /** 1 = single, 2 = double, 3 = triple. Aromatic bonds store 1 with type 'aromatic'. */
  order: BondOrder;
  type: BondType;
}

export interface MoleculeGraph {
  atoms: GraphAtom[];
  bonds: GraphBond[];
}

export type Difficulty = 'strict' | 'advanced' | 'sandbox';

export interface RuleOptions {
  difficulty: Difficulty;
  /** Ionic mode: metals + non-metals form ions and total charge must balance. */
  ionic?: boolean;
}

export type RejectCode =
  | 'OK'
  | 'SAME_ATOM'
  | 'MISSING_ATOM'
  | 'ALREADY_BONDED'
  | 'NOBLE_GAS'
  | 'VALENCY_EXCEEDED'
  | 'OCTET_EXCEEDED'
  | 'RADICAL_BLOCKED'
  | 'HYPERVALENT_BLOCKED'
  | 'IONIC_MODE_REQUIRED'
  | 'CHARGE_IMBALANCE'
  | 'STERIC_CLASH'
  | 'COORDINATION_LIMIT'
  | 'SELF_REACTION';

export interface BondCheck {
  ok: boolean;
  code: RejectCode;
  /** Short machine reason, surfaced in red toasts. */
  reason: string;
  /** Full JARVIS sentence (read aloud + printed in the log). */
  speech: string;
  /** 'error' blocks the action, 'warn' allows it with a toast. */
  severity: 'error' | 'warn';
}

export interface AtomAnalysis {
  id: string;
  element: string;
  bondSum: number;
  sigma: number;
  pi: number;
  lonePairs: number;
  formalCharge: number;
  shellElectrons: number;
  /** Shared (non-dative, non-ionic) bond order sum — the donor's valence usage. */
  covalentBondSum: number;
  /** Number of dative bonds touching this atom. */
  dative: number;
  /** True when at least one bond is delocalised (aromatic). */
  hasAromatic: boolean;
  octetSatisfied: boolean;
  radical: boolean;
  hybridization: HybridizationInfo;
  /** Index into the molecule — 0 based, stable ordering used by the UI. */
  isCentral: boolean;
  oxidationState: number;
}

export interface MoleculeAnalysis {
  formula: string;
  hillFormula: string;
  molarMass: number;
  atoms: AtomAnalysis[];
  /** Central atom = highest σ degree (tie-break: heavier, then not hydrogen). */
  centralAtomId: string | null;
  central: AtomAnalysis | null;
  hybridization: string;
  stericNumber: number;
  electronGeometry: string;
  molecularShape: string;
  bondAngle: number;
  bondAngleLabel: string;
  sigmaCount: number;
  piCount: number;
  lonePairCount: number;
  netCharge: number;
  chargeLabel: string;
  polarity: 'nonpolar' | 'polar' | 'ionic';
  dipoleNote: string;
  aromaticRings: string[][];
  isAromatic: boolean;
  stability: StabilityReport;
  /** Name from the known-molecule database, else generated by naming.ts */
  knownName?: string;
  iupac?: string;
  uses?: string[];
  hazards?: string[];
  funFact?: string;
  /** "isomer of butan-2-ol" etc. when the formula matches a known molecule with
   *  different connectivity. */
  isomerOf?: string;
  fragmentCount: number;
}

/* --------------------------------------------------------------- helpers */

export function atomById(g: MoleculeGraph, id: string): GraphAtom | undefined {
  return g.atoms.find((a) => a.id === id);
}

/** Sum of bond orders around an atom. Aromatic bonds count as 1.5. */
export function bondSumOf(g: MoleculeGraph, id: string): number {
  return g.bonds.reduce((s, b) => {
    if (b.a !== id && b.b !== id) return s;
    return s + (b.type === 'aromatic' ? 1.5 : b.order);
  }, 0);
}

export function sigmaCountOf(g: MoleculeGraph, id: string): number {
  return g.bonds.filter((b) => b.a === id || b.b === id).length;
}

export function piCountOf(g: MoleculeGraph, id: string): number {
  return g.bonds.reduce((s, b) => {
    if (b.a !== id && b.b !== id) return s;
    return s + (b.type === 'aromatic' ? 0.5 : Math.max(0, b.order - 1));
  }, 0);
}

/**
 * Bonds whose electron pairs are genuinely SHARED around this atom — i.e. everything
 * except dative (donated by the ligand) and ionic (transferred) bonds. This is what
 * valency, lone pairs and formal charge are computed from.
 */
export function covalentBondSumOf(g: MoleculeGraph, id: string): number {
  return g.bonds.reduce((s, b) => {
    if (b.a !== id && b.b !== id) return s;
    if (b.type === 'coordinate' || b.type === 'ionic') return s;
    return s + (b.type === 'aromatic' ? 1.5 : b.order);
  }, 0);
}

/**
 * Valency "usage" for the ceiling test. Aromatic bonds are worth 1.5 electrons
 * pairs for ELECTRON COUNTING, but a delocalised ring bond does not consume an
 * extra unit of valency — caffeine's ring nitrogen makes three σ bonds and donates
 * its lone pair, it is not four-valent.
 */
export function valenceUsageOf(g: MoleculeGraph, id: string): number {
  const aromatic = g.bonds.some((b) => (b.a === id || b.b === id) && b.type === 'aromatic');
  return aromatic ? sigmaCountOf(g, id) : covalentBondSumOf(g, id);
}

/**
 * Delocalised (aromatic) atoms need their own bookkeeping, because a ring bond is
 * worth 1.5 electron pairs — but the atom only DONATES one electron to the π system
 * (benzene C, pyridine N) or two (pyrrole N, furan O, caffeine's amide N).
 *
 *   π electrons donated = 1 when (V − charge − σ) is odd, else 2
 *   lone pairs          = (V − charge − σ − π) / 2        (pairs NOT in the π cloud)
 *   shell electrons     = 2·(σ + 1 π bond + lone pairs)
 */
export function aromaticShell(
  g: MoleculeGraph,
  id: string,
): { lp: number; shell: number; fc: number; sigma: number; pi: number } | null {
  const bonds = g.bonds.filter((b) => b.a === id || b.b === id);
  if (!bonds.some((b) => b.type === 'aromatic')) return null;
  const atom = atomById(g, id);
  if (!atom) return null;
  const V = getElement(atom.element).valenceElectrons;
  const charge = atom.charge ?? 0;
  const sigma = bonds.length;
  const remaining = V - charge - sigma;
  const pi = Math.abs(remaining % 2) === 1 ? 1 : 2;
  const lp = Math.max(0, (remaining - pi) / 2);
  return {
    lp,
    shell: 2 * lp + 2 * (sigma + 1),
    fc: V - 2 * lp - sigma - pi,
    sigma,
    pi,
  };
}

/** Number of dative (coordinate) bonds touching this atom. */
export function coordinateCountOf(g: MoleculeGraph, id: string): number {
  return g.bonds.filter((b) => b.type === 'coordinate' && (b.a === id || b.b === id)).length;
}

export function neighboursOf(g: MoleculeGraph, id: string): string[] {
  const out: string[] = [];
  for (const b of g.bonds) {
    if (b.a === id) out.push(b.b);
    else if (b.b === id) out.push(b.a);
  }
  return out;
}

export function getBond(g: MoleculeGraph, a: string, b: string): GraphBond | undefined {
  return g.bonds.find((x) => (x.a === a && x.b === b) || (x.a === b && x.b === a));
}

export function isMetal(symbol: string): boolean {
  return getElement(symbol).isMetal;
}

/* ------------------------------------------------------- molecular formula */

/** Hill notation: C first, H second, then all others alphabetically. */
export function hillFormula(counts: Record<string, number>): string {
  const parts: string[] = [];
  const c = counts.C;
  if (c) parts.push(c > 1 ? `C${c}` : 'C');
  const h = counts.H;
  if (h) parts.push(h > 1 ? `H${h}` : 'H');
  Object.keys(counts)
    .filter((s) => s !== 'C' && s !== 'H')
    .sort()
    .forEach((s) => parts.push(counts[s] > 1 ? `${s}${counts[s]}` : s));
  return parts.join('');
}

/** Structural-ish formula, e.g. "CH3CH2OH" — falls back to Hill. */
export function structuralFormula(g: MoleculeGraph): string {
  if (g.atoms.length === 0) return '';
  const groups: Record<string, number> = {};
  for (const a of g.atoms) groups[a.element] = (groups[a.element] ?? 0) + 1;
  return hillFormula(groups);
}

export function molarMass(g: MoleculeGraph): number {
  return g.atoms.reduce((m, a) => m + getElement(a.element).mass, 0);
}

/* ------------------------------------------------------------- canBond() */

/**
 * THE gatekeeper. Every bond attempt in the app calls this first.
 * Returns `{ ok: false, reason }` with a real chemistry explanation when the
 * requested bond would produce an impossible species.
 */
export function canBond(
  g: MoleculeGraph,
  aId: string,
  bId: string,
  order: BondOrder,
  opts: RuleOptions,
  type: BondType = 'covalent',
): BondCheck {
  const pass = (speech = ''): BondCheck => ({ ok: true, code: 'OK', reason: '', speech, severity: 'warn' });
  const fail = (code: RejectCode, reason: string, speech: string, severity: 'error' | 'warn' = 'error'): BondCheck => ({
    ok: false, code, reason, speech, severity,
  });

  if (aId === bId) return fail('SAME_ATOM', 'An atom cannot bond to itself.', 'An atom cannot bond to itself, sir.');
  const A = atomById(g, aId);
  const B = atomById(g, bId);
  if (!A || !B) return fail('MISSING_ATOM', 'Atom not found.', 'I cannot find that atom.');

  const eA = getElement(A.element);
  const eB = getElement(B.element);

  if (getBond(g, aId, bId)) {
    return fail(
      'ALREADY_BONDED',
      `${A.element}–${B.element} bond already exists — double-pinch to change bond order.`,
      'Those atoms are already bonded. Pinch twice to promote the bond order.',
    );
  }

  // (c) Noble gases. Xe/Kr are legitimate in ADVANCED/SANDBOX (XeF4, KrF2).
  if (eA.isNobleGas || eB.isNobleGas) {
    const ng = eA.isNobleGas ? eA : eB;
    const isChemistryNoble = ng.symbol === 'Xe' || ng.symbol === 'Kr';
    if (!isChemistryNoble || opts.difficulty === 'strict') {
      return fail(
        'NOBLE_GAS',
        `${ng.name} has a full valence shell — it cannot form bonds${opts.difficulty === 'strict' ? ' in Strict mode' : ''}.`,
        `${ng.name} has a complete valence shell. ${opts.difficulty === 'strict'
          ? 'Noble gas bonding is disabled in Strict mode.'
          : 'Only xenon and krypton form real compounds, and only with fluorine or oxygen.'}`,
      );
    }
    // Xe/Kr in advanced/sandbox: warn but allow.
  }

  const sumA = bondSumOf(g, aId);
  const sumB = bondSumOf(g, bId);
  const useA = valenceUsageOf(g, aId);
  const useB = valenceUsageOf(g, bId);
  const maxA = effectiveMaxValence(A.element, A.charge ?? 0);
  const maxB = effectiveMaxValence(B.element, B.charge ?? 0);

  // (a) Valency limit.
  if (useA + order > maxA) {
    return fail(
      'VALENCY_EXCEEDED',
      `${A.element} already has ${fmtNum(sumA)} bond${sumA === 1 ? '' : 's'}; maximum is ${maxA}.`,
      `Rejected. ${A.element} is already using ${fmtNum(sumA)} of its ${maxA} valence bonds. ${valencyHint(A.element)}`,
    );
  }
  if (useB + order > maxB) {
    return fail(
      'VALENCY_EXCEEDED',
      `${B.element} already has ${fmtNum(sumB)} bond${sumB === 1 ? '' : 's'}; maximum is ${maxB}.`,
      `Rejected. ${B.element} is already using ${fmtNum(sumB)} of its ${maxB} valence bonds. ${valencyHint(B.element)}`,
    );
  }

  // (b) Octet / duet rule. Period 2 can never exceed 8; period >= 3 may expand.
  const aromA = aromaticShell(g, aId);
  const aromB = aromaticShell(g, bId);
  const shellA = aromA
    ? 2 * aromA.lp + 2 * (aromA.sigma + 1 + order - (order > 1 ? 1 : 0))
    : sumA + order + 2 * lonePairs(A.element, sumA + order, A.charge ?? 0);
  const shellB = aromB
    ? 2 * aromB.lp + 2 * (aromB.sigma + 1 + order - (order > 1 ? 1 : 0))
    : sumB + order + 2 * lonePairs(B.element, sumB + order, B.charge ?? 0);
  const limitA = octetLimit(A.element);
  const limitB = octetLimit(B.element);
  if (shellA > limitA) {
    return fail(
      eA.canExpandOctet ? 'HYPERVALENT_BLOCKED' : 'OCTET_EXCEEDED',
      `${A.element} would hold ${fmtNum(shellA)} electrons; limit is ${limitA}.`,
      `${A.element} would be surrounded by ${fmtNum(shellA)} electrons. ${eA.canExpandOctet
        ? `Even hypervalent ${A.element} tops out at ${limitA}.`
        : `A period-${eA.period} element can never exceed the octet.`}`,
    );
  }
  if (shellB > limitB) {
    return fail(
      eB.canExpandOctet ? 'HYPERVALENT_BLOCKED' : 'OCTET_EXCEEDED',
      `${B.element} would hold ${fmtNum(shellB)} electrons; limit is ${limitB}.`,
      `${B.element} would be surrounded by ${fmtNum(shellB)} electrons. ${eB.canExpandOctet
        ? `Even hypervalent ${B.element} tops out at ${limitB}.`
        : `A period-${eB.period} element can never exceed the octet.`}`,
    );
  }

  // ---- Dative / coordinate bonds (coordination chemistry, §6) ----------------
  // The ligand DONATES a lone pair, so its valence is not consumed: we only check
  // (i) the metal has a free coordination site and (ii) the donor owns a lone pair.
  if (type === 'coordinate') {
    const donor = eA.isMetal ? B : A;
    const donorId = eA.isMetal ? bId : aId;
    const metal = eA.isMetal ? A : B;
    const metalId = eA.isMetal ? aId : bId;
    const mEl = getElement(metal.element);
    const sites = sigmaCountOf(g, metalId);
    const maxSites = mEl.category === 'transition' ? 6 : 4;
    if (sites >= maxSites) {
      return fail(
        'COORDINATION_LIMIT',
        `${metal.element} already has ${sites} ligands (max ${maxSites}).`,
        `That metal centre already holds ${sites} ligands, sir. ${maxSites} is the coordination limit.`,
      );
    }
    const cov = covalentBondSumOf(g, donorId);
    const available = lonePairs(donor.element, cov, donor.charge ?? 0) - coordinateCountOf(g, donorId);
    if (available < 1) {
      return fail(
        'VALENCY_EXCEEDED',
        `${donor.element} has no lone pair left to donate.`,
        `${donor.element} has no free lone pair to donate to the metal centre.`,
      );
    }
    return pass();
  }

  // (d) Ionic mode: a metal meeting a non-metal is an electron transfer, not a
  // shared pair. In covalent mode we still allow it but flag the polarity.
  const metalPair = eA.isMetal !== eB.isMetal;
  if (metalPair && opts.difficulty === 'strict' && !opts.ionic) {
    return fail(
      'IONIC_MODE_REQUIRED',
      'Metal + non-metal forms an ionic bond — enable Ionic mode.',
      'A metal and a non-metal do not share electrons, sir. Enable Ionic mode and I shall balance the charges.',
    );
  }

  // Radical / odd-electron check (f).
  if (opts.difficulty === 'strict') {
    const radical = willBeRadical(A.element, sumA + order, A.charge ?? 0) || willBeRadical(B.element, sumB + order, B.charge ?? 0);
    if (radical) {
      return fail(
        'RADICAL_BLOCKED',
        'Would create a radical (unpaired electron) — blocked in Strict mode.',
        'That would leave an unpaired electron. Radicals are disabled in Strict mode.',
      );
    }
  }

  // (g) Coordination limit for transition-metal centres (max 6 ligands).
  if (eA.isMetal && eA.category === 'transition' && sigmaCountOf(g, aId) >= 6) {
    return fail('COORDINATION_LIMIT', `${A.element} already has 6 ligands (octahedral).`, 'Six ligands is the octahedral limit for that metal centre.');
  }
  if (eB.isMetal && eB.category === 'transition' && sigmaCountOf(g, bId) >= 6) {
    return fail('COORDINATION_LIMIT', `${B.element} already has 6 ligands (octahedral).`, 'Six ligands is the octahedral limit for that metal centre.');
  }

  // (d) Ionic charge balance preview.
  if (opts.ionic && metalPair) {
    const preview = [...g.atoms];
    const q = preview.length ? netFormalCharge(g) : 0;
    if (Math.abs(q) > 0) {
      // Not a hard reject: the user may still add the balancing ion.
      return pass();
    }
  }

  return pass();
}

function willBeRadical(symbol: string, bondSum: number, charge: number): boolean {
  const V = getElement(symbol).valenceElectrons;
  const lp = lonePairs(symbol, bondSum, charge);
  const shell = 2 * lp + 2 * bondSum;
  // Odd electron count ⇒ radical (e.g. CH3• has C with 3 bonds and 0 lp ⇒ 6 e⁻… that
  // is an octet violation too). We treat "odd shell electrons" as radical.
  return Math.abs(shell % 2) === 1 || (V - charge - bondSum) % 2 === 1;
}

function fmtNum(n: number): string {
  return Number.isInteger(n) ? String(n) : n.toFixed(1);
}

function valencyHint(symbol: string): string {
  const el = getElement(symbol);
  const list = el.allowedValences.join(', ');
  return `${el.name} normally forms ${list} bond${el.allowedValences[0] === 1 ? '' : 's'}.`;
}

/* ------------------------------------------------------- steric clash (g) */

export interface Vec3Like { x: number; y: number; z: number }

/**
 * Reject a placement when the new atom's sphere would intersect an existing atom.
 * Uses van der Waals radii with a `tolerance` (1.0 = touching, <1 = allow slight
 * interpenetration which is normal for bonded atoms).
 */
export interface PlacedAtom {
  id: string;
  element: string;
  position: Vec3Like;
}

export function checkPlacement(
  others: PlacedAtom[],
  element: string,
  at: Vec3Like,
  tolerance = 0.85,
): { ok: boolean; clashesWith?: string; distance?: number; reason?: string } {
  const rNew = getElement(element).vdwRadius / 100;
  for (const o of others) {
    const dx = o.position.x - at.x, dy = o.position.y - at.y, dz = o.position.z - at.z;
    const d = Math.sqrt(dx * dx + dy * dy + dz * dz);
    const rOld = getElement(o.element).vdwRadius / 100;
    const min = (rNew + rOld) * tolerance;
    if (d < min) {
      return {
        ok: false,
        clashesWith: o.id,
        distance: d,
        reason: `Steric clash: ${d.toFixed(2)} Å between ${element} and ${o.element} (minimum ${min.toFixed(2)} Å).`,
      };
    }
  }
  return { ok: true };
}

/* -------------------------------------------------- formal charge & ions */

export function netFormalCharge(g: MoleculeGraph): number {
  return g.atoms.reduce((s, a) => s + formalCharge(a.element, bondSumOf(g, a.id), undefined, a.charge ?? 0), 0);
}

/** (d) In ionic mode the total charge must balance before "complete". */
export function checkIonicBalance(g: MoleculeGraph): { balanced: boolean; net: number; message: string } {
  const net = netFormalCharge(g);
  const hasMetal = g.atoms.some((a) => getElement(a.element).isMetal);
  if (!hasMetal) return { balanced: true, net, message: '' };
  if (net === 0) return { balanced: true, net, message: 'Charges balanced.' };
  return {
    balanced: false,
    net,
    message: `Charge imbalance: net ${formatCharge(net)}. Add ${net > 0 ? 'an anion' : 'a cation'} to neutralise.`,
  };
}

/* -------------------------------------------------------- ring detection */

/** Enumerate simple rings up to `maxSize` atoms (DFS, cheap for our sizes). */
export function findRings(g: MoleculeGraph, maxSize = 8): string[][] {
  const adj = new Map<string, string[]>();
  for (const a of g.atoms) adj.set(a.id, []);
  for (const b of g.bonds) {
    adj.get(b.a)?.push(b.b);
    adj.get(b.b)?.push(b.a);
  }
  const rings = new Set<string>();
  const result: string[][] = [];

  const dfs = (start: string, current: string, path: string[], visited: Set<string>) => {
    if (path.length > maxSize) return;
    for (const next of adj.get(current) ?? []) {
      if (next === start && path.length >= 3) {
        const key = [...path].sort().join('|');
        if (!rings.has(key)) {
          rings.add(key);
          result.push([...path]);
        }
        continue;
      }
      if (visited.has(next) || next < start) continue;
      visited.add(next);
      path.push(next);
      dfs(start, next, path, visited);
      path.pop();
      visited.delete(next);
    }
  };

  for (const a of g.atoms) {
    dfs(a.id, a.id, [a.id], new Set([a.id]));
  }
  return result;
}

/**
 * (j) Hückel aromaticity: planar ring, every atom sp², π electron count = 4n+2.
 * Each in-ring double bond contributes 2 e⁻; a heteroatom with a lone pair that is
 * part of the ring π system (pyrrole-type O/N/S) contributes 2 e⁻.
 */
export function findAromaticRings(g: MoleculeGraph): string[][] {
  const aromatic: string[][] = [];
  for (const ring of findRings(g, 7)) {
    if (ring.length !== 6 && ring.length !== 5) continue;
    const idx = new Set(ring);
    let allSp2 = true;
    let pi = 0;
    for (const id of ring) {
      const atom = atomById(g, id)!;
      const el = getElement(atom.element);
      const inRingDouble = g.bonds.some(
        (b) => (b.a === id || b.b === id) && idx.has(b.a) && idx.has(b.b) && (b.order >= 2 || b.type === 'aromatic'),
      );
      if (inRingDouble) {
        pi += 1; // one atom of a double bond ⇒ 1 electron, counted per atom
        continue;
      }
      // No double bond: contributes a lone pair only if it is O/N/S with a free pair.
      if (['N', 'O', 'S'].includes(atom.element) && bondSumOf(g, id) <= 3) {
        pi += 2;
        continue;
      }
      // Cationic carbon (tropylium) contributes 0 — still sp2.
      if (el.symbol === 'C' && (atom.charge ?? 0) > 0) continue;
      allSp2 = false;
      break;
    }
    if (!allSp2) continue;
    if (pi >= 2 && (pi - 2) % 4 === 0) aromatic.push(ring);
  }
  return aromatic;
}

/* ------------------------------------------------- canonical form / isomers */

/**
 * Weisfeiler–Lehman style canonical signature. Two molecules with the same Hill
 * formula but different signatures are constitutional isomers.
 */
export function canonicalSignature(g: MoleculeGraph): string {
  if (g.atoms.length === 0) return '';
  const ids = g.atoms.map((a) => a.id);
  let labels = new Map<string, string>();
  for (const a of g.atoms) {
    const deg = sigmaCountOf(g, a.id);
    const sum = bondSumOf(g, a.id);
    labels.set(a.id, `${a.element}:${deg}:${sum}:${a.charge ?? 0}`);
  }
  for (let iter = 0; iter < 4; iter++) {
    const next = new Map<string, string>();
    for (const id of ids) {
      const neigh = neighboursOf(g, id)
        .map((n) => labels.get(n) ?? '')
        .sort()
        .join(',');
      next.set(id, `${labels.get(id)}[${neigh}]`);
    }
    // Compress labels to stable ranks.
    const uniq = [...new Set([...next.values()])].sort();
    const rank = new Map(uniq.map((v, i) => [v, String(i)]));
    labels = new Map(ids.map((id) => [id, rank.get(next.get(id)!)!]));
  }
  const perAtom = ids
    .map((id) => {
      const a = atomById(g, id)!;
      return `${a.element}${labels.get(id)}`;
    })
    .sort()
    .join('|');
  return perAtom;
}

export interface KnownMolecule {
  formula: string;
  smiles: string;
  name: string;
  iupac: string;
  uses: string[];
  hazards: string[];
  hybridization?: string;
  geometry?: string;
  central?: string;
  funFact?: string;
  tags?: string[];
}

export const KNOWN: KnownMolecule[] = KNOWN_MOLECULES as KnownMolecule[];

/**
 * Strip a trailing charge written with UNICODE superscripts: "NH4⁺" → "NH4",
 * "SO4²⁻" → "SO4". We deliberately only strip superscript digits so that the "4"
 * in "NH4⁺" is never mistaken for part of the charge.
 */
export const stripCharge = (f: string): string => f.replace(/[\s]*[⁰¹²³⁴⁵⁶⁷⁸⁹]*[⁺⁻＋−]+$/, '');

/**
 * Order-independent element-count key: "H2SO4", "H2O4S" and "O4SH2" all give the
 * same key, so lookups keep working no matter which notation the JSON uses.
 */
export function elementKey(formula: string): string {
  const cleaned = stripCharge(formula).replace(/\s+/g, '');
  const counts = new Map<string, number>();
  const re = /([A-Z][a-z]?)(\d*)/g;
  let m: RegExpExecArray | null;
  let matched = '';
  while ((m = re.exec(cleaned))) {
    matched += m[0];
    const sym = m[1];
    if (!ELEMENT_TABLE[sym]) continue;
    counts.set(sym, (counts.get(sym) ?? 0) + (m[2] ? Number(m[2]) : 1));
  }
  // If the regex failed to consume the string (weird notation), fall back to the raw text.
  if (matched.replace(/\d/g, '').length === 0) return cleaned;
  return [...counts.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([s, n]) => `${s}${n}`).join('');
}

const KNOWN_BY_KEY: Map<string, KnownMolecule[]> = (() => {
  const map = new Map<string, KnownMolecule[]>();
  for (const k of KNOWN) {
    const key = elementKey(k.formula);
    const list = map.get(key) ?? [];
    list.push(k);
    map.set(key, list);
  }
  return map;
})();

/** Look up known-molecule entries by formula (order/charge insensitive). */
export function findKnownByFormula(formula: string): KnownMolecule | undefined {
  return KNOWN_BY_KEY.get(elementKey(formula))?.[0];
}

export function findAllKnownByFormula(formula: string): KnownMolecule[] {
  return KNOWN_BY_KEY.get(elementKey(formula)) ?? [];
}

/** (k) Isomer detection against the database. */
export function detectIsomer(g: MoleculeGraph): string | undefined {
  const formula = structuralFormula(g);
  if (!formula) return undefined;
  const matches = findAllKnownByFormula(formula);
  if (matches.length === 0) return undefined;
  const sig = canonicalSignature(g);
  const exact = matches.find((m) => m.smiles && smilesSignature(m.smiles) === sig);
  if (exact) return undefined;
  return matches[0].name;
}

/** Cheap canonical signature for a SMILES-ish string (symmetry-free, good enough
 *  for database matching because our DB entries are written canonically). */
export function smilesSignature(smiles: string): string {
  return smiles.replace(/\s+/g, '');
}

/* ------------------------------------------------------------ analysis */

/**
 * Pick the "central" atom the explanation card talks about.
 * Ranking: never a hydrogen (unless the molecule is pure hydrogen), then the most
 * NON-HYDROGEN neighbours, then the highest degree. This makes the carboxyl carbon
 * of acetic acid the centre rather than the methyl carbon.
 */
export function centralAtomOf(g: MoleculeGraph): GraphAtom | null {
  if (g.atoms.length === 0) return null;
  let best = g.atoms[0];
  let bestScore = -Infinity;
  for (const a of g.atoms) {
    const el = getElement(a.element);
    const nbrs = neighboursOf(g, a.id);
    const deg = nbrs.length;
    const heavy = nbrs.filter((n) => atomById(g, n)?.element !== 'H').length;
    const score = (a.element === 'H' ? -1e6 : 0) + heavy * 1000 + deg * 10 + el.mass / 100;
    if (score > bestScore) {
      bestScore = score;
      best = a;
    }
  }
  return best;
}

/**
 * Electron bookkeeping for one atom, with support for dative bonds.
 *
 * For a LIGAND (non-metal donor) the donated pair is counted as bonding in the
 * electron shell but is still "owned" by the donor for formal-charge purposes,
 * so NH3 stays neutral when it coordinates:  FC = 5 − 2(1) − 3 = 0.
 * For a METAL centre we report the explicit charge and its coordination number.
 */
export function analyzeAtom(g: MoleculeGraph, id: string): AtomAnalysis {
  const a = atomById(g, id)!;
  const el = getElement(a.element);
  const charge = a.charge ?? 0;
  const sum = bondSumOf(g, id);
  const sigma = sigmaCountOf(g, id);
  const pi = piCountOf(g, id);
  const cov = covalentBondSumOf(g, id);
  const dative = coordinateCountOf(g, id);

  let lp: number;
  let fc: number;
  let shell: number;
  const arom = aromaticShell(g, id);
  if (arom) {
    lp = arom.lp;
    fc = arom.fc;
    shell = arom.shell;
  } else if (el.isMetal) {
    lp = 0;
    fc = charge;
    shell = 2 * sum; // coordination electrons only — the octet rule does not apply
  } else {
    const lpBefore = lonePairs(a.element, cov, charge);
    lp = Math.max(0, lpBefore - dative);
    fc = formalCharge(a.element, cov, lpBefore);
    shell = 2 * lp + 2 * (cov + dative);
  }

  const limit = octetLimit(a.element);
  const os = neighboursOf(g, id).reduce((s, nId) => {
    const n = atomById(g, nId)!;
    const b = getBond(g, id, nId)!;
    const dEN = getElement(n.element).electronegativity - el.electronegativity;
    if (Math.abs(dEN) < 0.05) return s;
    return s + (dEN > 0 ? b.order : -b.order);
  }, 0) + (a.charge ?? 0);
  return {
    id,
    element: a.element,
    bondSum: sum,
    sigma,
    pi,
    lonePairs: lp,
    formalCharge: fc,
    shellElectrons: shell,
    covalentBondSum: cov,
    dative,
    hasAromatic: g.bonds.some((b) => (b.a === id || b.b === id) && b.type === 'aromatic'),
    octetSatisfied: el.isMetal ? true : shell >= limit || (el.period >= 3 && shell >= 8) || shell === limit,
    radical: !el.isMetal && Math.abs(shell % 2) === 1,
    hybridization: analyzeHybridization(sigma, lp, pi),
    isCentral: false,
    oxidationState: os,
  };
}

/** Polarity from electronegativity differences + shape symmetry. */
function analyzePolarity(
  g: MoleculeGraph,
  central: AtomAnalysis | null,
  positions?: Record<string, Vec3Like>,
): { polarity: 'nonpolar' | 'polar' | 'ionic'; note: string } {
  if (g.atoms.length <= 1) return { polarity: 'nonpolar', note: 'single atom' };
  const anyIonic = g.bonds.some((b) => b.type === 'ionic');
  const hasMetal = g.atoms.some((a) => getElement(a.element).isMetal);
  if (anyIonic || hasMetal) return { polarity: 'ionic', note: 'ionic lattice — full charge separation' };

  let maxDEN = 0;
  for (const b of g.bonds) {
    const A = atomById(g, b.a)!, B = atomById(g, b.b)!;
    maxDEN = Math.max(maxDEN, Math.abs(getElement(A.element).electronegativity - getElement(B.element).electronegativity));
  }
  if (maxDEN < 0.4) return { polarity: 'nonpolar', note: `ΔEN ${maxDEN.toFixed(2)} < 0.4 — essentially nonpolar covalent` };

  // Vector sum of bond dipoles when 3D positions are supplied.
  if (positions && central) {
    const c = positions[central.id];
    if (c) {
      let vx = 0, vy = 0, vz = 0;
      for (const nId of neighboursOf(g, central.id)) {
        const p = positions[nId];
        if (!p) continue;
        const n = atomById(g, nId)!;
        const dEN = getElement(n.element).electronegativity - getElement(central.element).electronegativity;
        const dx = p.x - c.x, dy = p.y - c.y, dz = p.z - c.z;
        const len = Math.hypot(dx, dy, dz) || 1;
        vx += (dx / len) * dEN; vy += (dy / len) * dEN; vz += (dz / len) * dEN;
      }
      const mag = Math.hypot(vx, vy, vz);
      if (mag < 0.05) return { polarity: 'nonpolar', note: 'bond dipoles cancel by symmetry (ΔEN > 0.4 but µ ≈ 0)' };
      return { polarity: 'polar', note: `net dipole µ ≈ ${mag.toFixed(2)} (arbitrary units)` };
    }
  }

  // Fallback: symmetric shapes with identical terminals are nonpolar.
  if (central) {
    const terms = neighboursOf(g, central.id).map((id) => atomById(g, id)!.element);
    const identical = terms.every((t) => t === terms[0]);
    const symmetric = ['linear', 'trigonal planar', 'tetrahedral', 'octahedral', 'square planar', 'trigonal bipyramidal'];
    if (identical && central.lonePairs === 0 && symmetric.includes(central.hybridization.molecularShape)) {
      return { polarity: 'nonpolar', note: `symmetric ${central.hybridization.molecularShape} geometry cancels the dipoles` };
    }
  }
  return { polarity: 'polar', note: `ΔEN ${maxDEN.toFixed(2)} with asymmetric geometry` };
}

/** The single call the HUD, JARVIS card, quiz and campaign all use. */
export function analyzeMolecule(
  g: MoleculeGraph,
  opts: RuleOptions = { difficulty: 'sandbox' },
  positions?: Record<string, Vec3Like>,
): MoleculeAnalysis {
  const atoms = g.atoms.map((a) => analyzeAtom(g, a.id));
  const centralAtom = centralAtomOf(g);
  const central = centralAtom ? (atoms.find((x) => x.id === centralAtom.id) ?? null) : null;
  if (central) central.isCentral = true;

  const counts: Record<string, number> = {};
  for (const a of g.atoms) counts[a.element] = (counts[a.element] ?? 0) + 1;
  const formula = hillFormula(counts);

  const sigmaCount = g.bonds.filter((b) => b.type !== 'hydrogen').length;
  const piCount = g.bonds.reduce((s, b) => s + (b.type === 'aromatic' ? 1 : Math.max(0, b.order - 1)), 0);
  const aromaticRings = findAromaticRings(g);
  const polarity = analyzePolarity(g, central, positions);
  // Sum the per-atom formal charges (dative-bond aware) rather than recomputing.
  const net = atoms.reduce((sum, a) => sum + a.formalCharge, 0);

  const known = findKnownByFormula(formula);
  const isomerOf = known ? undefined : detectIsomer(g);
  const isomerKnown = isomerOf ? KNOWN.find((k) => k.name === isomerOf) : undefined;

  const stability = classifyStability(g, atoms, opts);

  // Fragment count (connected components) — a "molecule" should be one piece.
  const fragmentCount = countFragments(g);

  return {
    formula,
    hillFormula: formula,
    molarMass: molarMass(g),
    atoms,
    centralAtomId: central?.id ?? null,
    central,
    hybridization: central?.hybridization.label ?? '—',
    stericNumber: central?.hybridization.stericNumber ?? 0,
    electronGeometry: central?.hybridization.electronGeometry ?? '—',
    molecularShape: central?.hybridization.molecularShape ?? '—',
    bondAngle: central?.hybridization.angle ?? 0,
    bondAngleLabel: central?.hybridization.angleLabel ?? '—',
    sigmaCount,
    piCount,
    lonePairCount: central?.lonePairs ?? 0,
    netCharge: net,
    chargeLabel: formatCharge(net),
    polarity: polarity.polarity,
    dipoleNote: polarity.note,
    aromaticRings,
    isAromatic: aromaticRings.length > 0,
    stability,
    knownName: known?.name,
    iupac: known?.iupac,
    uses: known?.uses,
    hazards: known?.hazards,
    funFact: known?.funFact,
    isomerOf: isomerOf ? `isomer of ${isomerOf}${isomerKnown?.iupac ? ` (${isomerKnown.iupac})` : ''}` : undefined,
    fragmentCount,
  };
}

export function countFragments(g: MoleculeGraph): number {
  const adj = new Map<string, string[]>();
  for (const a of g.atoms) adj.set(a.id, []);
  for (const b of g.bonds) {
    adj.get(b.a)?.push(b.b);
    adj.get(b.b)?.push(b.a);
  }
  const seen = new Set<string>();
  let n = 0;
  for (const a of g.atoms) {
    if (seen.has(a.id)) continue;
    n++;
    const stack = [a.id];
    while (stack.length) {
      const cur = stack.pop()!;
      if (seen.has(cur)) continue;
      seen.add(cur);
      for (const nx of adj.get(cur) ?? []) if (!seen.has(nx)) stack.push(nx);
    }
  }
  return n;
}

/* ------------------------------------------------------- graph utilities */

export function cloneGraph(g: MoleculeGraph): MoleculeGraph {
  return { atoms: g.atoms.map((a) => ({ ...a })), bonds: g.bonds.map((b) => ({ ...b })) };
}

export function emptyGraph(): MoleculeGraph {
  return { atoms: [], bonds: [] };
}

/** Remove an atom and all its bonds (used by FIST = delete). */
export function removeAtom(g: MoleculeGraph, id: string): MoleculeGraph {
  return { atoms: g.atoms.filter((a) => a.id !== id), bonds: g.bonds.filter((b) => b.a !== id && b.b !== id) };
}

/** Build a graph from a SMILES-like fragment spec used by the level/ghost data. */
export function graphFromAtoms(spec: { element: string; charge?: number; bonds: { to: number; order: BondOrder; type?: BondType }[] }[]): MoleculeGraph {
  const atoms: GraphAtom[] = spec.map((s, i) => ({ id: `a${i}`, element: s.element, charge: s.charge ?? 0 }));
  const bonds: GraphBond[] = [];
  spec.forEach((s, i) => {
    s.bonds.forEach((b, j) => {
      if (b.to <= i) return; // each bond declared once (from the lower index)
      bonds.push({ id: `b${i}_${j}`, a: `a${i}`, b: `a${b.to}`, order: b.order, type: b.type ?? 'covalent' });
    });
  });
  return { atoms, bonds };
}

/**
 * Preferred (neutral) valence used to add implicit hydrogens — the standard
 * SMILES "organic subset" valences: B3, C4, N3, O2, P3, S2, F/Cl/Br/I 1.
 */
export function preferredValence(symbol: string): number {
  return getElement(symbol).allowedValences[0] ?? getElement(symbol).maxValence;
}

const NO_IMPLICIT_H = new Set(['H', 'He', 'Ne', 'Ar', 'Na', 'K', 'Mg', 'Ca', 'Li', 'Fe', 'Cu', 'Co', 'Ni', 'Zn', 'Ag', 'Cr', 'Mn', 'Al']);

/**
 * Add implicit hydrogens: every uncharged main-group atom gets
 * `preferredValence − bondSum − explicitH` hydrogens. Turn this off for literal
 * graph specs (graphFromAtoms) where the author writes every atom.
 */
export function addImplicitHydrogens(g: MoleculeGraph, explicitH?: Map<string, number>): MoleculeGraph {
  const out = cloneGraph(g);
  let extra = 0;
  for (const a of g.atoms) {
    if (NO_IMPLICIT_H.has(a.element) || (a.charge ?? 0) !== 0) continue;
    const sum = bondSumOf(g, a.id);
    const have = explicitH?.get(a.id) ?? 0;
    // Aromatic atoms have half-integer bond sums (1.5 per delocalised bond); floor
    // so that a purine fusion carbon asking for 1.5 hydrogens gets 1, not 2.
    const need = Math.floor(Math.max(0, preferredValence(a.element) - sum - have) + 1e-9);
    for (let i = 0; i < need; i++) {
      const id = `h${extra++}_${a.id}`;
      out.atoms.push({ id, element: 'H', charge: 0 });
      out.bonds.push({ id: `hb${id}`, a: a.id, b: id, order: 1, type: 'covalent' });
    }
  }
  return out;
}

/**
 * Parse the compact SMILES subset used by levels.json / ghost skeletons:
 *   atoms (organic subset + brackets), - = # : bonds, branches, ring digits,
 *   aromatic lowercase atoms, bracket atoms with H-count and charge ([NH4+], [nH], [O-]).
 * Implicit hydrogens are added unless `implicitH` is false.
 */
/**
 * "[Na+].[Cl-]" parses as two disconnected atoms, but a salt is ONE lattice.
 * This joins every isolated metal ion to the most negative non-metal partner with
 * an explicit ionic bond, so fragment counts, naming and charge sums stay sane.
 */
function linkIonicFragments(g: MoleculeGraph): void {
  const parent = new Map<string, string>();
  const find = (x: string): string => (parent.get(x) === x ? x : (parent.set(x, find(parent.get(x) ?? x)), find(parent.get(x) ?? x)));
  for (const a of g.atoms) parent.set(a.id, a.id);
  for (const b of g.bonds) {
    const ra = find(b.a), rb = find(b.b);
    if (ra !== rb) parent.set(ra, rb);
  }
  const loneMetals = g.atoms.filter(
    (a) => getElement(a.element).isMetal && !g.bonds.some((b) => b.a === a.id || b.b === a.id),
  );
  for (const m of loneMetals) {
    const candidates = g.atoms.filter((a) => !getElement(a.element).isMetal && find(a.id) !== find(m.id));
    if (candidates.length === 0) continue;
    const target =
      candidates.find((a) => (a.charge ?? 0) < 0) ??
      candidates.find((a) => ['O', 'F', 'Cl', 'Br', 'I', 'S', 'N'].includes(a.element)) ??
      candidates[0];
    g.bonds.push({ id: `ionic_${m.id}_${target.id}`, a: m.id, b: target.id, order: 1, type: 'ionic' });
  }
}

/**
 * Decide what a metal–non-metal bond actually IS, because the SMILES subset has no
 * notation for it:
 *   • transition metal  → dative/coordinate (the ligand donates a lone pair)
 *   • s/p-block metal   → ionic, with charges assigned so both ions get a full shell
 */
export function classifyMetalBonds(g: MoleculeGraph): void {
  for (const b of g.bonds) {
    if (b.type !== 'covalent') continue;
    const A = atomById(g, b.a);
    const B = atomById(g, b.b);
    if (!A || !B) continue;
    const eA = getElement(A.element);
    const eB = getElement(B.element);
    const metalIsA = eA.isMetal && !eB.isMetal;
    const metalIsB = eB.isMetal && !eA.isMetal;
    if (!metalIsA && !metalIsB) continue;
    const metalEl = metalIsA ? eA : eB;
    const metalAtom = metalIsA ? A : B;
    const otherAtom = metalIsA ? B : A;
    const otherEl = metalIsA ? eB : eA;
    if (metalEl.category === 'transition') {
      b.type = 'coordinate';
      continue;
    }
    b.type = 'ionic';
    // The anion takes enough electrons to complete its octet (Cl −1, O −2, N −3).
    const anionCharge = -(8 - otherEl.valenceElectrons) || -1;
    if ((otherAtom.charge ?? 0) === 0) otherAtom.charge = Math.min(-1, anionCharge);
  }

  // Balance the cations afterwards, once every ionic bond is known.
  for (const a of g.atoms) {
    const el = getElement(a.element);
    if (!el.isMetal || (a.charge ?? 0) !== 0) continue;
    const partners = g.bonds.filter((b) => b.type === 'ionic' && (b.a === a.id || b.b === a.id));
    if (partners.length === 0) continue;
    const sum = partners.reduce((t, b) => {
      const otherId = b.a === a.id ? b.b : b.a;
      return t + Math.abs(atomById(g, otherId)?.charge ?? 1);
    }, 0);
    const preferred = el.commonOxidationStates[0] ?? sum;
    a.charge = Math.min(sum === 0 ? 0 : preferred, sum) || sum;
  }
}

export function graphFromSmilesLite(smiles: string, implicitH = true): MoleculeGraph {
  const g = emptyGraph();
  let atomIdx = 0;
  let hIdx = 0;
  const stack: string[] = [];
  let prev = '';
  let pending: BondOrder = 1;
  let pendingType: BondType = 'covalent';
  let prevAromatic = false;
  const ringOpen = new Map<string, { atom: string; order: BondOrder; type: BondType }>();
  const explicitH = new Map<string, number>();
  const aromaticAtoms = new Set<string>();

  const addAtom = (element: string, charge = 0): string => {
    const id = `a${atomIdx++}`;
    g.atoms.push({ id, element, charge });
    return id;
  };
  const addH = (parent: string): string => {
    const id = `h${hIdx++}`;
    g.atoms.push({ id, element: 'H', charge: 0 });
    bond(parent, id, 1, 'covalent');
    return id;
  };
  function bond(a: string, b: string, order: BondOrder, type: BondType) {
    if (!a || !b || a === b) return;
    if (getBond(g, a, b)) return;
    g.bonds.push({ id: `b${g.bonds.length}_${a}_${b}`, a, b, order, type });
  }
  const connect = (a: string, b: string) => {
    bond(a, b, pending, pendingType);
    pending = 1;
    pendingType = 'covalent';
  };

  let i = 0;
  while (i < smiles.length) {
    const ch = smiles[i];
    if (ch === '(') { stack.push(prev); i++; continue; }
    if (ch === ')') { prev = stack.pop() ?? prev; i++; continue; }
    if (ch === '-') { pending = 1; i++; continue; }
    if (ch === '=') { pending = 2; i++; continue; }
    if (ch === '#') { pending = 3; i++; continue; }
    if (ch === ':') { pending = 1; pendingType = 'aromatic'; i++; continue; }
    if (ch === '.') { prev = ''; i++; continue; }
    if (ch === '*' || ch === '@' || ch === '/' || ch === '\\') { i++; continue; }
    if (/[0-9]/.test(ch)) {
      if (ringOpen.has(ch) && prev) {
        const open = ringOpen.get(ch)!;
        bond(open.atom, prev, pending !== 1 ? pending : open.order, pending !== 1 ? pendingType : open.type);
        ringOpen.delete(ch);
      } else if (prev) {
        ringOpen.set(ch, { atom: prev, order: pending, type: pendingType });
      }
      pending = 1;
      pendingType = 'covalent';
      i++;
      continue;
    }
    if (ch === '[') {
      const close = smiles.indexOf(']', i);
      if (close < 0) break;
      const inner = smiles.slice(i + 1, close);
      i = close + 1;
      const m = /^([A-Za-z][a-z]?)(H\d*)?([+-]\d*)?/.exec(inner);
      if (!m) continue;
      const sym = m[1].charAt(0).toUpperCase() + m[1].slice(1);
      if (!ELEMENT_TABLE[sym]) continue;
      const charge = m[3] ? (m[3][0] === '+' ? 1 : -1) * (m[3].length > 1 ? Number(m[3].slice(1)) || 1 : 1) : 0;
      const hCount = m[2] ? (m[2].length > 1 ? Number(m[2].slice(1)) : 1) : 0;
      const id = addAtom(sym, charge);
      if (hCount > 0) explicitH.set(id, hCount);
      for (let k = 0; k < hCount; k++) addH(id);
      if (prev) connect(prev, id);
      prev = id;
      prevAromatic = false;
      continue;
    }
    const two = smiles.slice(i, i + 2);
    const aromatic = /[a-z]/.test(ch) && ch === ch.toLowerCase();
    const isTwoLetter = /^[A-Z][a-z]$/.test(two) && !!ELEMENT_TABLE[two];
    const sym = aromatic ? ch.toUpperCase() : isTwoLetter ? two : ch.toUpperCase();
    if (!ELEMENT_TABLE[sym]) { i++; continue; }
    const id = addAtom(sym, 0);
    if (aromatic) aromaticAtoms.add(id);
    if (prev) connect(prev, id);
    prev = id;
    prevAromatic = aromatic;
    i += !aromatic && isTwoLetter ? 2 : 1;
  }

  linkIonicFragments(g);
  classifyMetalBonds(g);

  // Bonds between two aromatic atoms become aromatic (Kekulé structures are normalised).
  for (const b of g.bonds) {
    if (aromaticAtoms.has(b.a) && aromaticAtoms.has(b.b) && b.type === 'covalent') b.type = 'aromatic';
  }

  return implicitH ? addImplicitHydrogens(g, explicitH) : g;
}

/** True when every atom satisfies its octet/duet and nothing is over-valent. */
export function isComplete(g: MoleculeGraph, opts: RuleOptions): boolean {
  if (g.atoms.length === 0) return false;
  const analysis = analyzeMolecule(g, opts);
  return analysis.stability.status !== 'impossible' && analysis.fragmentCount === 1;
}
